//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAP.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Benutzer
    {
        public Benutzer()
        {
            this.AlleBuchungen = new HashSet<Buchung>();
            this.AlleKontakte = new HashSet<Kontakt>();
            this.AlleRechnungen = new HashSet<Rechnung>();
            this.AlleStornierungen = new HashSet<Stornierung>();
        }
    
        public int Id { get; set; }
        public int BenutzerRolle_Id { get; set; }
        public int Firmen_Id { get; set; }
        public string Email { get; set; }
        public byte[] Passwort { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public bool active { get; set; }
    
        public virtual BenutzerRolle BenutzerRolle { get; set; }
        public virtual Firma Firma { get; set; }
        public virtual ICollection<Buchung> AlleBuchungen { get; set; }
        public virtual ICollection<Kontakt> AlleKontakte { get; set; }
        public virtual ICollection<Rechnung> AlleRechnungen { get; set; }
        public virtual ICollection<Stornierung> AlleStornierungen { get; set; }
    }
}
