//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAP.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class BenutzerRollen
    {
        public BenutzerRollen()
        {
            this.Benutzer = new HashSet<Benutzer>();
        }
    
        public int Id { get; set; }
        public string Beschreibung { get; set; }
        public bool active { get; set; }
    
        public virtual ICollection<Benutzer> Benutzer { get; set; }
    }
}
