//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAP.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public bill()
        {
            this.billdetails = new HashSet<billdetail>();
        }
    
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public int portaluser_id { get; set; }
    
        public virtual ICollection<billdetail> billdetails { get; set; }
        public virtual portaluser portaluser { get; set; }
    }
}
