//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAP.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public booking()
        {
            this.billdetails = new HashSet<billdetail>();
            this.bookingreversals = new HashSet<bookingreversal>();
        }
    
        public int id { get; set; }
        public int room_id { get; set; }
        public int portaluser_id { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual ICollection<billdetail> billdetails { get; set; }
        public virtual ICollection<bookingreversal> bookingreversals { get; set; }
        public virtual Benutzer portaluser { get; set; }
        public virtual room room { get; set; }
    }
}
