//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAP.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buchung
    {
        public Buchung()
        {
            this.AlleRechnungsDetails = new HashSet<RechnungsDetail>();
            this.AlleStornierungen = new HashSet<Stornierung>();
        }
    
        public int Id { get; set; }
        public int Raum_Id { get; set; }
        public int Benutzer_Id { get; set; }
        public System.DateTime Datum { get; set; }
    
        public virtual Benutzer Benutzer { get; set; }
        public virtual Raum Räume { get; set; }
        public virtual ICollection<RechnungsDetail> AlleRechnungsDetails { get; set; }
        public virtual ICollection<Stornierung> AlleStornierungen { get; set; }
    }
}
