//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAP.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firma
    {
        public Firma()
        {
            this.AlleBenutzer = new HashSet<Benutzer>();
            this.AlleKontakte = new HashSet<Kontakt>();
        }
    
        public int Id { get; set; }
        public string FirmenName { get; set; }
        public string Plz { get; set; }
        public string Stadt { get; set; }
        public string Straße { get; set; }
        public string Hausnummer { get; set; }
    
        public virtual ICollection<Benutzer> AlleBenutzer { get; set; }
        public virtual ICollection<Kontakt> AlleKontakte { get; set; }
    }
}
