//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAP.Logic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITIN20LAPEntities : DbContext
    {
        public ITIN20LAPEntities()
            : base("name=ITIN20LAPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<billdetails> Allbilldetails { get; set; }
        public DbSet<bills> Allbills { get; set; }
        public DbSet<bookingreversals> Allbookingreversals { get; set; }
        public DbSet<bookings> Allbookings { get; set; }
        public DbSet<companies> Allcompanies { get; set; }
        public DbSet<contacts> Allcontacts { get; set; }
        public DbSet<facilities> Allfacilities { get; set; }
        public DbSet<furnishings> furnishings { get; set; }
        public DbSet<portalroles> Allportalroles { get; set; }
        public DbSet<portalusers> Allportalusers { get; set; }
        public DbSet<roomfurnishings> Allroomfurnishings { get; set; }
        public DbSet<rooms> Allrooms { get; set; }
        public DbSet<Log> Log { get; set; }
    }
}
