//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAP.Logic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITIN20LAPEntities : DbContext
    {
        public ITIN20LAPEntities()
            : base("name=ITIN20LAPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<billdetail> billdetails { get; set; }
        public DbSet<bill> bills { get; set; }
        public DbSet<bookingreversal> bookingreversals { get; set; }
        public DbSet<booking> bookings { get; set; }
        public DbSet<company> companies { get; set; }
        public DbSet<contact> contacts { get; set; }
        public DbSet<facility> facilities { get; set; }
        public DbSet<furnishing> furnishings { get; set; }
        public DbSet<PortalRollen> PortalRollens { get; set; }
        public DbSet<Benutzer> Benutzers { get; set; }
        public DbSet<roomfurnishing> roomfurnishings { get; set; }
        public DbSet<room> rooms { get; set; }
        public DbSet<Log> Logs { get; set; }
    }
}
