//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAP.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontakte
    {
        public int Id { get; set; }
        public int Benutzer_Id { get; set; }
        public int Firmen_Id { get; set; }
    
        public virtual Benutzer Benutzer { get; set; }
        public virtual Firmen Firmen { get; set; }
    }
}
