//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAP.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaumEinrichtung
    {
        public int Id { get; set; }
        public int Raum_Id { get; set; }
        public int Einrichtung_Id { get; set; }
    
        public virtual Einrichtung Einrichtung { get; set; }
        public virtual Raum Raum { get; set; }
    }
}
