//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAP.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rechnungen
    {
        public Rechnungen()
        {
            this.RechnungsDetails = new HashSet<RechnungsDetails>();
        }
    
        public int Id { get; set; }
        public System.DateTime Datum { get; set; }
        public int Benutzer_Id { get; set; }
    
        public virtual Benutzer Benutzer { get; set; }
        public virtual ICollection<RechnungsDetails> RechnungsDetails { get; set; }
    }
}
