//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAP.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Räume
    {
        public Räume()
        {
            this.Buchungen = new HashSet<Buchungen>();
            this.RaumEinrichtungen = new HashSet<RaumEinrichtungen>();
        }
    
        public int Id { get; set; }
        public int Gebäude_Id { get; set; }
        public string Beschreibung { get; set; }
    
        public virtual ICollection<Buchungen> Buchungen { get; set; }
        public virtual Gebäude Gebäude { get; set; }
        public virtual ICollection<RaumEinrichtungen> RaumEinrichtungen { get; set; }
    }
}
